### ISSUE TITLE
movies in 2015

### ISSUE THREAD

**Issue by baohongfei** [baohongfei/2015#3]
#1 西雅图夜未眠

**Comment by BaoHongfei** [comment]
#2 死亡诗社

**Comment by BaoHongfei** [comment]
#3 玩具总动员

**Comment by BaoHongfei** [comment]
玩具总动员3

**Comment by BaoHongfei** [comment]
#5 智取威虎山 todo

**Comment by BaoHongfei** [comment]
指环王 系列

**Comment by BaoHongfei** [comment]
闻香识女人

**Comment by BaoHongfei** [comment]
#5 2001哈利波特与魔法石 Harry.Potter.and.the.Sorcerers.Stone

**Comment by BaoHongfei** [comment]
#6 2002哈利波特与密室 Harry.Potter.and.the.Chamber.of.Secrets

**Comment by BaoHongfei** [comment]
#7 2004哈利波特与阿兹卡班囚徒 Harry.Potter.and.the.Prisoner.of.Azkaban

**Comment by BaoHongfei** [comment]
#8 2005哈利波特与火焰杯 Harry.Potter.and.the.Goblet.of.Fire

**Comment by BaoHongfei** [comment]
#9 2007哈利波特与凤凰社 Harry.Potter.and.the.Order.of.the.Phoenix

**Comment by BaoHongfei** [comment]
#10 1994肖申克的救赎 The Shawshank Redemption

**Comment by BaoHongfei** [comment]
#11 2014智取威虎山 The Taking of Tiger Mountain
