### ISSUE TITLE
amazon

### ISSUE THREAD

**Issue by baohongfei** [baohongfei/2015#4]
http://blog.csdn.net/threeidiots/article/details/41678751
ssh -i keypair1.pem ec2-user@54.200.147.47

**Comment by BaoHongfei** [comment]
筋斗云VPN
MxVPN

**Comment by BaoHongfei** [comment]
ytbit.com
最近几周开始 IPSec 协议会导致 IP 被墙，为了保障用户可以持续使用，云梯暂时关闭了大部分线路的 L2TP/IPSec 协议，请大家优先使用 PPTP 协议。
